### ISSUE TITLE
How can I make the stack to be flat?

### ISSUE THREAD

**Issue by bysdan42** [aaronbond/Swipe-Deck#28]
Is there an option to make a stack of say 10 cards (I'm using RelativeLayout as the main element for the card, so it doesn't have a shadow) flat without shadow at all?

**Comment by aaronbond** [comment]
yeah should be possible although it's not something i've tried. 

i'm not really sure what having ten cards on screen at once will do (if anything) to performance but just use something without a drop shadow instead of the card view (say a linearlayout or something you whip up yourself) and then set the CARD_SPACING attribute to zero and they should render underneath each other.
