### ISSUE TITLE
How to display different images in swipedeck?

### ISSUE THREAD

**Issue by suhaassreedhar** [aaronbond/Swipe-Deck#4]
Hi, i need to know how to display different images when you swipe the cards instead of only one image?

**Comment by aaronbond** [comment]
you will have to explain more clearly what it is that you want to achieve.

give me an example

**Comment by suhaassreedhar** [comment]
In the swipedeck your displaying only single image(i mean the burger image), i need to know how to display different images when we swipe the cards...i.e.if you swipe the first card, it should display other image in the next card which is not as the previous one...

**Comment by aaronbond** [comment]
It's only like that because it's an example.

It works the exact same way as any other adapter view in android, if you've ever used a recyclerview or a list view or anything like that you should be familiar with how to do this.

in the instructions on the main page you can see a very simple adapter class the purpose of which is to adapt data to an adapter view. this would be where you do the logic for setting different images.

think of it like this:

```
 --------------------------------------              ------------              ---------
|        Collection of Objects        | ------- |  Adapter | -------- |  View  |
 --------------------------------------              ------------              ---------
```

That stuff in the collection of objects might be URL's to an image, the adapter will take those URL's and insert the image into the relevant image view in the card. 

you pass that collection of whatever you want to the adapter which sets up the view. all the logic for setting text / images etc in the cards goes in that adapter.

**Comment by suhaassreedhar** [comment]
Okay thank you...

**Comment by aaronbond** [comment]
no problems, let me know if you have any additional questions.
